import { GroupBox, LineEdit, Button } from "std-widgets.slint";

import { VerticalBox , HorizontalBox, Button} from "std-widgets.slint";
//import { BorderlessWindow } from "widget/borderless-window.slint";
import { Content } from "content.slint";

export component MainWindow inherits Window {
    title: "Clipboard";
    preferred-width: 480px;
    preferred-height: 320px;

    in property <image> window_icon: @image-url("./icon/icon.png");

    icon: window_icon;

    Content {}
}